python compute_scores.py --task passkey
python compute_scores.py --task number_string
python compute_scores.py --task kv_retrieval
python compute_scores.py --task math_find
python compute_scores.py --task math_calc
python compute_scores.py --task longbook_qa_eng
python compute_scores.py --task longbook_choice_eng
python compute_scores.py --task longbook_sum_eng
python compute_scores.py --task longbook_qa_chn
python compute_scores.py --task longdialogue_qa_eng
python compute_scores.py --task code_run
python compute_scores.py --task code_debug
